language: ruby

install: "echo skip bundle install"

script:
  - ssh -o StrictHostKeyChecking=no git@github.com
  - git clone git@github.com:Vanuan/redmine_backlogs_rails3.git
  - cd redmine_backlogs_rails3
  - touch 1
  - git add 1
  - git commit -m "travis"
  - git push
