language: ruby

install: "echo skip bundle install"

script:
  - ssh-keygen -R github.com
  - ssh-keygen -R 207.97.227.239
  - ssh-keygen -R github.com,207.97.227.239
  - ssh-keyscan -H github.com,207.97.227.239 >> ~/.ssh/known_hosts
  - ssh-keyscan -H 207.97.227.239 >> ~/.ssh/known_hosts
  - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
  - git clone git@github.com:Vanuan/redmine_backlogs_rails3.git
  - cd redmine_backlogs_rails3
  - touch 1
  - git add 1
  - git commit -m "travis"
  - git push
